### ISSUE TITLE
Inventory entries

### ISSUE THREAD

**Issue by fridthi** [BB2A-Anthony/dolibarr#44]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Feature Request# Automatic inventory entries
[*Short description*]
I noteced that when creating client's or vendor's invoice , only purchasing or selling entries are creating in accounting, But not entries related to inventory moves in accounting
## Use case
[*Verbose description*]

## Suggested implementation
[*Verbose description*]
Inventory accounts should be requested in Item card and automatically be used when creating invoices 
## Suggested steps
[*List of tasks to achieve goal*]

**Comment by BB2A-Anthony** [comment]
Mouve your issue in base branch it's a forke.

[https://github.com/Dolibarr/dolibarr/issues](https://github.com/Dolibarr/dolibarr/issues)
